.NH 2
Introduction
.NH 3
Taking Counsciouness Seriously
.LP
About consciousness as an \[lq]illusion\[rq]:
.MN right
Page xii
.MN
.QP
.vs 12
.ps 10
I have little idea what this could even mean.
It seems to me that we are surer of the existence of conscious experience than we are of anything else in the world.
.LP
Doesn't an illusion require that there are things that are real,
and things that just appear to be real,
i.e.,
those illusions.
.PP
Chalmers starts with three constraints
.IP a. 
Take consciousness seriously
.IP b.
Take science seriously
.IP c.
Accept consciousness as natural phenomenon
.PP
Chalmers considers two problems or perhaps kinds of problems:
The easy problems of consciousness that build  upon the assumption that it can be understood  by analysing cognition and behaviours.
The hard problem is that those problems are insufficient for understanding the consciousness.
These two sets of problems are on the opposite ends of a \[lq]Great Divide\[rq].
If you hold that the answer to an easy problem explains it all,
you will get one theory.
I you base your theory on the existence of hard problems it will be very different.
.QP
.MN right
Page xiv
.MN
I argue that reductive explanations of consciousness impossible and I even argue for a form of dualism.
But this is just a part of the scientific process.
Certain sorts of explanation turn out to not work,
so we need to embrace other sorts of explanation instead.
Everything I say here is compatible with the results of contemporary science;
our picture of the natural world is broadened, not overturned.
.NH 2
Foundations
.NH 3
Two Concepts of Mind
.LP
What is consciousness?
.PP
.MN right
Page 4
.MN
Chalmers don't use any definition of his own.
His definition is formulated through
.[ 
#
Thomas Nagel Bat
.]
.QP
.vs 12
.ps 10
We can say that a being is is conscious if there is \f[I]something it is like\f[P] to be that being.
.NH 3
Phenomenal and Psychological 
.LP
.MN right
Page 11
.MN
.QP
.vs 12
.ps 10
On the phenomenal concept,
mind is characterised by the way it feels;
on the psychological by what it does.
.LP
.MN right 
Page 14\[en]15
.MN
Functionalism include groups of positions sharing the idea that there exist mental states that cause behaviours.
.LP
.MN right
Page 16
.MN
.QP
.vs 12
.ps 10
At a first approximation, 
phenomenal concepts deal with the first-person aspects of mind,
and psychological concepts deal with the third person aspects.
.NH 3
The double life of mental terms
.LP
.MN right 
Page 18
.MN
.QP
.vs 12
.ps 10
A good test for whether a mental notion $M$ is primarily psychological is to ask oneself:
Could something be an instance of $M$ without any particular associated phenomenal quality?
.NH 3
The two mind-body problems
.LP
.MN right
Page 24
.MN
The fact that we have have two kinds of mental properties has consequences.
.QP
.vs 12
.ps 10
[...] effect of dividing the mind-body problem into two: an easy part and a hard part.
The psychological aspects of mind pose many problems for cognitive science [...] but they pose no deep metaphysical enigmas.
.LP
Learning and memory are functions that belong to the easy ones.
They might be connected with enormous technical problems,
but hardly any metaphysical ones.
They are \[oq]puzzles\[cq] not \[oq]mysteries\[cq].
.QP
.MN right
Page 25
.MN
.vs 12
.ps 10
The phenomenal aspects of mind are a different matter.
Here,
the mind-body problem is as baffling as it ever was.
The impressive progress of the physical and cognitive sciences has not shed significant light on the question of how and why cognitive functioning is accompanied by conscious experience.
The progress in the understanding of the mind has almostentirely centered on the explanation of behaviour.
This progress leaves the question of consious experience untouched.
.LP
Chalmers refers to this problem as the mind-mind problem.
.NH 3
Explaining consciousness versus explaining awareness
.LP
.MN right
Page 31
.MN
Finally Chalmers simplifies his vocabulary
.QP
.vs 12
.ps 10
In what follows,
I revert to using \[oq]consciusness\[cq] to refer to phenomenal conciousness alone.
When I wish to use the psychological notions,
I will speak of \[oq]psychological consciousness\[cq] or \[oq]awareness.\[cq]
It is phenomenal consciusness with which I will mostly be concerned.
.NH 2
Supervenience and Explanation
.NH 3
Supervenience
.QP
.MN right
Page 33
.MN
.vs 12
.ps 10
The
.I A-facts
and
.I B-facts
about the world are the facts concerning the instantiation and distribution of A-properties and B-properties. [...]
The template for the definition of supervenience is the following:
B-properties
.I supervene 
on A-properties if no two possible with respect to their A-properties while differing  in their B-properties.
.LP
.MN right
Page 33\[en]34
.MN
\f[BI]Local and global supervenience\f[P] \[em]
.QP
.vs 12
.ps 10
B-properties supervene
.I locally
on A-properties if the A-properties of an
.I individual
determine the B-properties of that individual.
.LP
.MN right
Page 34
.MN
Chalmers understands \[oq]global\[cq] as \[oq]an entire universe\[cq]
.QP
.vs 12
.ps 10
B-properties supervenes globally on A-properties,
by contrast,
if the A-facts of the entire
.I world
determines the the B-facts:
if there are no two possible worlds identical with respect to A-properties,
but differing with respect to their B-properties.
.LP
.MN right
Page 34\[en]35
.MN
\f[BI]Logical and natural supervenience\f[P]
.QP
.vs 12
.ps 10
B-properties supervene
.I logically
on A-properties if no two logically \f[I]possible situations\f[P] are identical with respect to their A-properties but distinct with respect to their B-properties.
.LP
Hence, logical supervenience is not defined in terms of deducabilityh in any system of formal logic,
what matters is logically possible worlds (or situations).
