.NH 2
Introduction
.NH 3
Taking Counsciouness Seriously
.LP
.MNinit symmetric 3c 4c 1n HR 8z 9.6p red ""
.
About consciousness as an \[lq]illusion\[rq]:
.MN right
Page xii
.[
Chalmers 1996
.]
.MN
.QP
.vs 12
.ps 10
I have little idea what this could even mean.
It seems to me that we are surer of the existence of conscious experience than we are of anything else in the world.
.LP
Doesn't an illusion require that there are things that are real,
and things that just appear to be real,
i.e.,
those illusions.

