.NH 2
Functions
.NH 3
Functional analysis by
.[ 
#
Cummins functional analysis
.]
.LP
Functional analysis starts with Hempel and Nagel, sais Cummins.
(A) The reason for functional characerization in science is to explain the presence of an item $i$ in a system $s$.
(B) For something to perform its function is for it to have certain function in $s$.
Now we can say that presence of $i$ in $s$ characterized since $i$ is present in $s$
.BI because
it has certain effects on $s$.
