.NH 2
Functions
.NH 3
Functional analysis by
.[ 
#
Cummins functional analysis
.]
.LP
.MN right
p. 741
.MN
Functional analysis starts with Hempel and Nagel, sais Cummins.
(A) The reason for functional characerization in science is to explain the presence of an item $i$ in a system $s$.
(B) For something to perform its function is for it to have certain function in $s$.
Now we can say that presence of $i$ in $s$ characterized since $i$ is present in $s$
.BI because
it has certain effects on $s$.
.LP
Something is wrong,
in particular with (A) above.
.QP
.MN right
p. 745
.MN
.vs 12
.ps 10
An attempt to explain the presence of something by appeal to what it does\[em]its function\[em]is bound to leave unexplained why something else that does the same thing-a functional equivalent-isn't there instead.
